//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Сourse.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<int> IdOrderProduct { get; set; }
        public Nullable<int> IdServiceOrder { get; set; }
        public Nullable<decimal> Cost { get; set; }
    
        public virtual User User { get; set; }
        public virtual OrderProduct OrderProduct { get; set; }
    }
}
